# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

#站点基础配置
title: Young's
subTitle: Just your Neighbor Young!
description: folked from PIZn
url: http://yycsxz.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: Home
    url: /index.html
    icon: icon-home
    class: home
  - text: Archives
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: About
    url: /contact.html
    icon: icon-envelope-alt
    class: none
  - text: Lab
    url: /lab.html
    icon: icon-heart
    class: none
  - text: GitHub
    url: https://github.com/yycsxz
    icon: icon-github
    class: none

page:
  - text: Tags
    url: /archives.html
    last: true
  - text: Links
    url: /links.html
    last: true
  - text: About 
    url: /contact.html
    last: false

author:
  name: Young's
